---
dns_records_add:
  - view: private
    zone: {{ full_dns_domain }}
    entries:
{% for host in groups['openshift'] %}
    - type: A
      hostname: {{ hostvars[host]['ansible_hostname'] }}
      ip: {{ hostvars[host]['dns_private_ip'] }}
{% endfor %}
  - view: public
    zone: {{ full_dns_domain}}
    entries:
{% for host in groups['openshift']%}
    - type: A
      hostname: {{ hostvars[host]['ansible_hostname'] }}
      ip: {{ hostvars[host]['dns_public_ip'] }}
{% endfor %}
