---
dns_records_add:
  - view: private
    zone: {{ full_dns_domain }}
    entries:
{% for host in groups[named_views_hostgroup] %}
    - type: A
      hostname: {{ hostvars[host]['ansible_hostname'] }}
      ip: {{ hostvars[host]['openstack']['private_v4'] }}
{% endfor %}
  - view: public
    zone: {{ full_dns_domain}}
    entries:
{% for host in groups[named_views_hostgroup]%}
    - type: A
      hostname: {{ hostvars[host]['ansible_hostname'] }}
      ip: {{ hostvars[host]['openstack']['public_v4'] }}
{% endfor %}
